# Generated by Django 2.0.7 on 2018-07-10 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('status_text', models.TextField()),
                ('is_open', models.BooleanField()),
                ('is_local_holiday', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.TextField()),
                ('prefix', models.URLField()),
                ('suffix', models.TextField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('website', models.URLField()),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Hour')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.Restaurant'),
        ),
    ]
