# Generated by Django 2.0.7 on 2018-07-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='referral_id',
            field=models.TextField(default=''),
        ),
    ]
