# Generated by Django 2.0.7 on 2018-07-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_restaurant_referral_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour',
            name='status',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='referral_id',
            field=models.TextField(default='', unique=True),
        ),
    ]
