# Generated by Django 2.0.7 on 2018-07-10 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180710_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='hour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Hour'),
        ),
    ]
